# Generated by Django 4.2.7 on 2024-01-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0003_post_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_photos/'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='title', max_length=25),
            preserve_default=False,
        ),
    ]
