# Generated by Django 4.2.7 on 2024-01-10 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0005_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='date_sent',
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default=datetime.datetime(2024, 1, 10, 17, 53, 17, 656362), max_length=50),
            preserve_default=False,
        ),
    ]
